### ISSUE TITLE
Error when i build iOS with release 2.7.2

### ISSUE THREAD

**Issue by SviatoslavSquirrel** [hyochan/expo-iap#114]
> Please use the [Discussion board](https://github.com/hyochan/expo-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

After enter the command 

npx expo install expo-iap ==> ok
cd ios ==> ok
pod install ==> ok
npm run ios ( expo run:ios ) ==> error 

**Expected Behavior**

› Preparing expo-modules-core Pods/ExpoModulesCore » ExpoModulesCore-Info.plist

❌  (node_modules/expo-iap/ios/ExpoIapModule.swift:272:56)

  270 |                 
  271 |                 var result: [String: Any?] = [
> 272 |                     "appTransactionID": appTransaction.appTransactionID,
      |                                                        ^ value of type 'AppTransaction' has no member 'appTransactionID'
  273 |                     "bundleID": appTransaction.bundleID,
  274 |                     "appVersion": appTransaction.appVersion,
  275 |                     "originalAppVersion": appTransaction.originalAppVersion,

› Signing   expo-modules-core Pods/ExpoModulesCore » ExpoModulesCore.framework
    Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'bluebow' from project 'bluebow')
    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')
    Run script build phase '[CP-User] [RN]Check rncore' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-FabricComponents' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-FabricComponents' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RCT-Folly' from project 'Pods')
    Run script build phase '[CP-User] Generate updates resources for expo-updates' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'fmt' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Yoga' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'ReactCommon' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-utils' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-runtimescheduler' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-rendererdebug' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-rendererconsistency' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-performancetimeline' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-nativeconfig' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-microtasksnativemodule' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-jserrorhandler' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-idlecallbacksnativemodule' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-graphics' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-featureflagsnativemodule' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-featureflags' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-domnativemodule' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-defaultsnativemodule' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-debug' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-RuntimeHermes' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-RuntimeCore' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-RuntimeApple' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-NativeModulesApple' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Mapbuffer' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-ImageManager' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-FabricImage' from project 'Pods')
    Run script build phase '[CP-User] [RN]Check rncore' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Fabric' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Fabric' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNReanimated' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'ReactCodegen' from project 'Pods')

› 1 error(s), and 36 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.

**Screenshots**

**Environment:**

- expo-iap: "expo-iap": "^2.7.2",
- expo : "expo": "~52.0.17",
- react-native: "react-native": "0.76.3",
- node : v22.9.0
- pod : 1.16.2
- xCode : Version 16.2 
- ruby -v : ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [arm64-darwin23]
- Platforms (iOS, Android, emulator, simulator, device): prb on iOS with simulator

**To Reproduce** Steps to reproduce the behavior:

After enter the command 

npx expo install expo-iap ==> ok
cd ios ==> ok
pod install ==> ok
npm run ios ( expo run:ios ) ==> error 

❌  (node_modules/expo-iap/ios/ExpoIapModule.swift:272:56)

  270 |                 
  271 |                 var result: [String: Any?] = [
> 272 |                     "appTransactionID": appTransaction.appTransactionID,
      |                                                        ^ value of type 'AppTransaction' has no member 'appTransactionID'
  273 |                     "bundleID": appTransaction.bundleID,
  274 |                     "appVersion": appTransaction.appVersion,
  275 |                     "originalAppVersion": appTransaction.originalAppVersion,

---

[Optional] **Additional Context**

**Comment by hyochan** [comment]
@SviatoslavSquirrel Thanks for the detailed report!

I'm currently unable to reproduce this issue on my end. The `expo-iap@2.7.2` build works fine both with local dev clients and EAS builds using the versions you listed.

This might be related to a specific configuration or environment. Would it be possible for you to provide a minimal reproducible example (e.g., a GitHub repo or zipped project) where the error occurs?

That would really help in pinpointing the issue more precisely 🙏

**Comment by hyochan** [comment]
I just created a fresh Expo app and installed version 2.7.2, and it's working well\! 🎉

Tested with:
- Fresh Expo app
- expo-iap@2.7.2

Everything is functioning as expected.

**Comment by richardvanderdys** [comment]
Same error for me.

expo-iap@2.7.2
Xcode 16.2
iPhone (18.5)
iOS deployment target: 16 (used `expo-build-properties` plugin)

**Comment by richardvanderdys** [comment]
Downgrading to `2.6.0` did not fix the issue for me

**Comment by hyochan** [comment]
> Same error for me.
> 
> expo-iap@2.7.2 Xcode 16.2 iPhone (18.5) iOS deployment target: 16 (used `expo-build-properties` plugin) SDK: iOS 18.2
> 
> ```
> ❌  (node_modules/expo-iap/ios/ExpoIapModule.swift:272:56)
> 
>   270 |
>   271 |                 var result: [String: Any?] = [
> > 272 |                     "appTransactionID": appTransaction.appTransactionID,
>       |                                                        ^ value of type 'AppTransaction' has no member 'appTransactionID'
>   273 |                     "bundleID": appTransaction.bundleID,
>   274 |                     "appVersion": appTransaction.appVersion,
>   275 |                     "originalAppVersion": appTransaction.originalAppVersion,
> ```

Could you try to upgrade Xcode to `16.4`?

**Comment by survivorsam** [comment]
> Downgrading to `2.6.0` did not fix the issue for me

@richardvanderdys 2.5.3 is the last stable version

**Comment by hyochan** [comment]
> > Downgrading to `2.6.0` did not fix the issue for me
> 
> [@richardvanderdys](https://github.com/richardvanderdys) 2.5.3 is the last stable version

I think this is very messy area in ios development, but I think upgrading xcode would fix this problem!

**Comment by hyochan** [comment]
I've just found that there could be a problem ios SDK version < `18.4`.

@ngethan Could you kindly test `expo-iap@2.7.4` which I just deployed?

**Comment by ngethan** [comment]
@hyochan happy to report updating to 2.7.4 fixed the AppTransaction error! However, I'm still receiving the iOS 15.0 or newer errors

<img width="270" height="188" alt="Image" src="https://github.com/user-attachments/assets/1320b99d-80c6-4933-860c-98b7c509d38e" />

**Comment by hyochan** [comment]
The additional issues you encountered are actually expected behavior. expo-iap exclusively supports StoreKit 2, which is only available from iOS 15.0 onwards.
Therefore, the "'Product' is only available in iOS 15.0 or newer" error messages are normal, and to use expo-iap, you'll need to set your project's minimum deployment target to iOS 15.0 or higher.
Currently, devices running iOS versions below 15 account for less than 5% of users worldwide. Typically, when targeting newer iOS versions for app deployment, users on older versions won't receive updates that include new features like in-app purchase modules.
Since the issue has been resolved, I'll close this now. Thank you!

**Comment by di-sukharev** [comment]
still experiencing the issue, created the https://github.com/hyochan/expo-iap/issues/127

i tried removing all caches, removing node_modules, updating react-native to 0.80.2

but it still fails in expo dev build, but for 0.80.2 the error is different

**Comment by hyochan** [comment]
@pikooli This issue is already closed, and the information provided isn’t sufficient to investigate the root cause.

It seems related to [this FAQ entry](https://expo-iap.hyo.dev/docs/guides/faq#what-version-of-xcode-should-i-use-for-ios-development). Please check the documentation for more details.

If you believe there’s still an actionable problem, feel free to open a new issue instead of replying to a closed one.
